//! Persisted repository lockfile data structures.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::EntityType;
use crate::state::{StateError, write_atomic};
use crate::types::{EntityId, Hash, LocationKey, RuntimeName};

const LOCKFILE_NAME: &str = "agentmesh.lock";
const LOCKFILE_HEADER: &str = "# agentmesh.lock - generated by AgentMesh, do not edit by hand\n";

/// Lockfile result type.
pub type Result<T> = std::result::Result<T, LockfileError>;

/// Errors produced while reading, validating, and writing lockfiles.
#[derive(Debug, Error)]
pub enum LockfileError {
    /// Reading the lockfile failed.
    #[error("failed to read lockfile at {}", path.display())]
    Read {
        /// Lockfile path.
        path: PathBuf,
        /// Source IO error.
        #[source]
        source: std::io::Error,
    },
    /// Parsing YAML failed.
    #[error("failed to parse lockfile at {}", path.display())]
    Parse {
        /// Lockfile path.
        path: PathBuf,
        /// Source parse error.
        #[source]
        source: serde_yml::Error,
    },
    /// Serializing YAML failed.
    #[error("failed to serialize lockfile")]
    Serialize {
        /// Source serialization error.
        #[source]
        source: serde_yml::Error,
    },
    /// The lockfile schema is newer than this binary supports.
    #[error("lockfile uses schema v{found}; upgrade required")]
    UnsupportedSchema {
        /// Schema found in the lockfile.
        found: u32,
        /// Highest schema supported by this binary.
        supported: u32,
    },
    /// A migration step is missing.
    #[error("no lockfile migration registered from schema v{from_schema} to v{to_schema}")]
    MissingMigration {
        /// Source schema version.
        from_schema: u32,
        /// Target schema version.
        to_schema: u32,
    },
    /// Atomic write failed.
    #[error(transparent)]
    State(#[from] StateError),
}

/// Current lockfile content version.
pub const LOCKFILE_CONTENT_VERSION: u32 = 1;

/// Current lockfile schema version.
pub const LOCKFILE_SCHEMA_VERSION: u32 = 1;

/// Highest lockfile schema version this build can read.
pub const MAX_SUPPORTED_LOCKFILE_SCHEMA: u32 = LOCKFILE_SCHEMA_VERSION;

/// AgentMesh repository lockfile shape.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Lockfile {
    /// Lockfile content version.
    pub version: u32,
    /// Lockfile schema version.
    pub schema: u32,
    /// Entity registry keyed by entity ID.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub entities: BTreeMap<EntityId, LockfileEntity>,
    /// Runtime-specific rendering overrides keyed by entity ID and runtime name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub overrides: BTreeMap<EntityId, BTreeMap<RuntimeName, OverrideEntry>>,
    /// Active adapter declarations keyed by runtime name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub adapters: BTreeMap<RuntimeName, AdapterDeclaration>,
}

impl Lockfile {
    /// Creates an empty lockfile at the current schema.
    #[must_use]
    pub fn empty() -> Self {
        Self {
            version: LOCKFILE_CONTENT_VERSION,
            schema: LOCKFILE_SCHEMA_VERSION,
            entities: BTreeMap::new(),
            overrides: BTreeMap::new(),
            adapters: BTreeMap::new(),
        }
    }

    /// Ensures this lockfile can be read by this binary.
    pub fn ensure_supported(&self) -> Result<()> {
        if self.schema > MAX_SUPPORTED_LOCKFILE_SCHEMA {
            return Err(LockfileError::UnsupportedSchema {
                found: self.schema,
                supported: MAX_SUPPORTED_LOCKFILE_SCHEMA,
            });
        }

        Ok(())
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::empty()
    }
}

/// A single entity entry in the repository lockfile.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LockfileEntity {
    /// Canonical entity type.
    #[serde(rename = "type")]
    pub entity_type: EntityType,
    /// Scope for instruction entities.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    /// Runtime and canonical locations for this entity.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub locations: BTreeMap<LocationKey, PathBuf>,
    /// Hash of the canonical entity representation.
    pub canonical_sha256: Hash,
    /// Hashes of the bytes last emitted to each location.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub emitted_native_sha256: BTreeMap<LocationKey, Hash>,
    /// Bounded import and sync lineage.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub lineage: Vec<LineageEntry>,
    /// Whether this entity has an unacknowledged conflict resolution.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pending_conflict_resolution: Option<bool>,
    /// Bounded rename history.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub rename_history: Vec<RenameRecord>,
    /// Optional explicit identity marker discovered in user content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id_pin: Option<EntityId>,
}

/// Lineage entry describing how an entity entered the canonical model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LineageEntry {
    /// Source path that supplied the entity.
    pub imported_from: PathBuf,
    /// ISO-8601 timestamp for the import.
    pub at: String,
    /// Actor that performed the import.
    pub by: String,
}

/// Rename record stored for identity continuity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RenameRecord {
    /// Previous path.
    pub from: PathBuf,
    /// Current path.
    pub to: PathBuf,
    /// ISO-8601 timestamp for the rename.
    pub at: String,
}

/// Runtime-specific override values applied during emit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
#[serde(transparent)]
pub struct OverrideEntry(pub BTreeMap<String, Value>);

/// Adapter declaration persisted in the lockfile.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdapterDeclaration {
    /// Adapter loading mode.
    pub mode: AdapterMode,
    /// Negotiated adapter protocol version.
    pub protocol_version: u32,
    /// Entity types the adapter supports.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub entities: Vec<EntityType>,
    /// Hook kinds installed by this adapter.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub hooks: Vec<HookKind>,
}

/// Adapter loading mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AdapterMode {
    /// First-party adapter linked into the single AgentMesh binary.
    Bundled,
}

/// Runtime hook category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum HookKind {
    /// Hook that runs after a runtime tool use.
    PostToolUse,
}

/// One lockfile schema migration step.
pub type MigrationFn = fn(Lockfile) -> Result<Lockfile>;

/// Version-dispatch table for lockfile migrations.
#[derive(Default)]
pub struct MigrationRegistry {
    target_schema: u32,
    migrations: BTreeMap<u32, MigrationFn>,
}

impl MigrationRegistry {
    /// Creates a registry that migrates to the current schema.
    #[must_use]
    pub fn current() -> Self {
        Self::new(LOCKFILE_SCHEMA_VERSION)
    }

    /// Creates a registry that migrates to a specific schema.
    #[must_use]
    pub fn new(target_schema: u32) -> Self {
        Self {
            target_schema,
            migrations: BTreeMap::new(),
        }
    }

    /// Registers a migration from one schema to the next schema.
    pub fn register(&mut self, from_schema: u32, migration: MigrationFn) {
        self.migrations.insert(from_schema, migration);
    }

    /// Runs migrations until the target schema is reached.
    pub fn migrate(&self, mut lockfile: Lockfile) -> Result<Lockfile> {
        while lockfile.schema < self.target_schema {
            let Some(migration) = self.migrations.get(&lockfile.schema) else {
                return Err(LockfileError::MissingMigration {
                    from_schema: lockfile.schema,
                    to_schema: lockfile.schema + 1,
                });
            };
            lockfile = migration(lockfile)?;
        }

        Ok(lockfile)
    }
}

/// Parses a lockfile from YAML and checks schema compatibility.
pub fn parse_lockfile(contents: &str) -> Result<Lockfile> {
    let lockfile =
        serde_yml::from_str::<Lockfile>(contents).map_err(|source| LockfileError::Parse {
            path: PathBuf::from(LOCKFILE_NAME),
            source,
        })?;
    lockfile.ensure_supported()?;
    MigrationRegistry::current().migrate(lockfile)
}

/// Serializes a lockfile with stable map ordering.
pub fn serialize_lockfile(lockfile: &Lockfile) -> Result<String> {
    lockfile.ensure_supported()?;
    let body =
        serde_yml::to_string(lockfile).map_err(|source| LockfileError::Serialize { source })?;
    let body = body.strip_prefix("---\n").unwrap_or(&body);

    Ok(format!("{LOCKFILE_HEADER}{body}"))
}

/// Reads `agentmesh.lock` from a repository root.
pub fn read_lockfile(repo_root: &Path) -> Result<Lockfile> {
    let path = repo_root.join(LOCKFILE_NAME);
    let contents = fs::read_to_string(&path).map_err(|source| LockfileError::Read {
        path: path.clone(),
        source,
    })?;
    serde_yml::from_str::<Lockfile>(&contents)
        .map_err(|source| LockfileError::Parse { path, source })
        .and_then(|lockfile| {
            lockfile.ensure_supported()?;
            MigrationRegistry::current().migrate(lockfile)
        })
}

/// Writes `agentmesh.lock` to a repository root atomically.
pub fn write_lockfile(repo_root: &Path, lockfile: &Lockfile) -> Result<()> {
    let path = repo_root.join(LOCKFILE_NAME);
    let contents = serialize_lockfile(lockfile)?;
    write_atomic(&path, contents.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    use super::{
        AdapterDeclaration, AdapterMode, HookKind, LOCKFILE_SCHEMA_VERSION, Lockfile,
        LockfileEntity, LockfileError, MigrationRegistry, parse_lockfile, serialize_lockfile,
    };
    use crate::EntityType;
    use crate::types::{EntityId, Hash, LocationKey, RuntimeName};

    fn valid_hash() -> Hash {
        match Hash::new("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef") {
            Ok(hash) => hash,
            Err(error) => panic!("test hash should be valid: {error}"),
        }
    }

    fn entity_id(value: &str) -> EntityId {
        match EntityId::new(value) {
            Ok(entity_id) => entity_id,
            Err(error) => panic!("test entity id should be valid: {error}"),
        }
    }

    fn location_key(value: &str) -> LocationKey {
        match LocationKey::new(value) {
            Ok(location_key) => location_key,
            Err(error) => panic!("test location key should be valid: {error}"),
        }
    }

    fn runtime_name(value: &str) -> RuntimeName {
        match RuntimeName::new(value) {
            Ok(runtime_name) => runtime_name,
            Err(error) => panic!("test runtime name should be valid: {error}"),
        }
    }

    #[test]
    fn lockfile_roundtrips_entity_shapes() {
        let mut lockfile = Lockfile::empty();
        let mut locations = BTreeMap::new();
        locations.insert(
            location_key(".ai"),
            "skills/security-review/SKILL.md".into(),
        );
        locations.insert(
            location_key(".claude"),
            "skills/security-review/SKILL.md".into(),
        );

        lockfile.entities.insert(
            entity_id("skill:security-review"),
            LockfileEntity {
                entity_type: EntityType::Skill,
                scope: None,
                locations,
                canonical_sha256: valid_hash(),
                emitted_native_sha256: BTreeMap::from([(location_key(".ai"), valid_hash())]),
                lineage: Vec::new(),
                pending_conflict_resolution: Some(true),
                rename_history: Vec::new(),
                id_pin: None,
            },
        );
        lockfile.adapters.insert(
            runtime_name("claude"),
            AdapterDeclaration {
                mode: AdapterMode::Bundled,
                protocol_version: 1,
                entities: vec![
                    EntityType::Instructions,
                    EntityType::Skill,
                    EntityType::Subagent,
                ],
                hooks: vec![HookKind::PostToolUse],
            },
        );

        let serialized = match serialize_lockfile(&lockfile) {
            Ok(serialized) => serialized,
            Err(error) => panic!("lockfile should serialize: {error}"),
        };
        let parsed = match parse_lockfile(&serialized) {
            Ok(parsed) => parsed,
            Err(error) => panic!("lockfile should parse: {error}"),
        };

        assert_eq!(parsed, lockfile);
    }

    #[test]
    fn serialization_is_stable_for_same_input() {
        let lockfile = Lockfile::empty();
        let first = serialize_lockfile(&lockfile);
        let second = serialize_lockfile(&lockfile);

        assert_eq!(first.ok(), second.ok());
    }

    #[test]
    fn rejects_newer_schema() {
        let mut lockfile = Lockfile::empty();
        lockfile.schema = LOCKFILE_SCHEMA_VERSION + 1;

        let error = serialize_lockfile(&lockfile).err();

        assert!(error.is_some());
    }

    #[test]
    fn parsing_newer_schema_reports_upgrade_needed() {
        let contents = format!("version: 1\nschema: {}\n", LOCKFILE_SCHEMA_VERSION + 1);

        let error = parse_lockfile(&contents).err();

        assert!(matches!(
            error,
            Some(LockfileError::UnsupportedSchema {
                found,
                supported
            }) if found == LOCKFILE_SCHEMA_VERSION + 1 && supported == LOCKFILE_SCHEMA_VERSION
        ));
    }

    #[test]
    fn stores_native_hashes_independently_from_canonical_hash() {
        let canonical_hash =
            Hash::new("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let native_hash =
            Hash::new("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb");
        let (Ok(canonical_hash), Ok(native_hash)) = (canonical_hash, native_hash) else {
            panic!("test hashes should be valid");
        };

        let entity = LockfileEntity {
            entity_type: EntityType::Subagent,
            scope: None,
            locations: BTreeMap::from([
                (
                    location_key(".ai"),
                    PathBuf::from(".ai/subagents/reviewer.md"),
                ),
                (
                    location_key(".codex"),
                    PathBuf::from(".codex/agents/reviewer.toml"),
                ),
            ]),
            canonical_sha256: canonical_hash.clone(),
            emitted_native_sha256: BTreeMap::from([(location_key(".codex"), native_hash.clone())]),
            lineage: Vec::new(),
            pending_conflict_resolution: None,
            rename_history: Vec::new(),
            id_pin: None,
        };

        assert_eq!(entity.canonical_sha256, canonical_hash);
        assert_eq!(
            entity.emitted_native_sha256.get(&location_key(".codex")),
            Some(&native_hash)
        );
    }

    #[test]
    fn migration_registry_dispatches_registered_steps() {
        fn migrate(mut lockfile: Lockfile) -> super::Result<Lockfile> {
            lockfile.schema += 1;
            Ok(lockfile)
        }

        let mut registry = MigrationRegistry::new(2);
        registry.register(1, migrate);

        let migrated = match registry.migrate(Lockfile::empty()) {
            Ok(migrated) => migrated,
            Err(error) => panic!("migration should run: {error}"),
        };

        assert_eq!(migrated.schema, 2);
    }
}
